In [3]:
import tensorflow as tf

v = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
with tf.Session() as sess:
    print(tf.clip_by_value(v, 2.5, 4.5).eval())

[[ 2.5  2.5  3. ]
 [ 4.   4.5  4.5]]


In [4]:
import tensorflow as tf

v = tf.constant([1.0, 2.0, 3.0])
with tf.Session() as sess:
    print(tf.log(v).eval())

[ 0.          0.69314718  1.09861231]


In [5]:
import tensorflow as tf

v1 = tf.constant([[1.0, 2.0], [3.0, 4.0]])
v2 = tf.constant([[5.0, 6.0], [7.0, 8.0]])
with tf.Session() as sess:
    print((v1 * v2).eval())
    print(tf.matmul(v1, v2).eval())

[[  5.  12.]
 [ 21.  32.]]
[[ 19.  22.]
 [ 43.  50.]]


In [8]:
import tensorflow as tf

v1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
v2 = tf.constant([3, 4, 5])
with tf.Session() as sess:
    print(tf.reduce_mean(v1).eval())
    print(tf.reduce_mean(v2).eval())

3.5
4


In [11]:
import tensorflow as tf

v1 = tf.constant([1.0, 2.0, 3.0, 4.0])
v2 = tf.constant([4.0, 3.0, 1.0, 1.0])
with tf.Session() as sess:
    print(tf.greater(v1, v2).eval())
    print(tf.where(tf.greater(v1, v2), v1, v2).eval())

[False False  True  True]
[ 4.  3.  3.  4.]
